export const SET_EMAIL = "SET_EMAIL"
export const SET_NAME = "SET_NAME"
export const SET_TOKEN = "SET_TOKEN"
export const SET_MATRICULE = "SET_MATRICULE"
export const SIGN_IN = "SIGN_IN"
export const SIGN_OUT = "SIGN_OUT"
